CREATE SEQUENCE TB_MANAGEDFILE_FID_SEQ
START WITH 1;

REVOKE ALL
ON TABLE TB_MANAGEDFILE_FID_SEQ
FROM PUBLIC;

GRANT SELECT, UPDATE
ON TABLE TB_MANAGEDFILE_FID_SEQ
TO PTOAPP;

COMMENT ON SEQUENCE TB_MANAGEDFILE_FID_SEQ
IS 'Sequence for managed file FID';

CREATE TABLE TB_MANAGEDFILE (
	CL_FID			BIGINT
	DEFAULT NEXTVAL('TB_MANAGEDFILE_FID_SEQ'),
	CL_DEVNAME		VARCHAR(200)
	NOT NULL,
	CL_NAME			VARCHAR(3600)
	NOT NULL,
	CL_CDATE		TIMESTAMP WITH TIME ZONE
	NOT NULL,
	CONSTRAINT CC_MANAGEDFILE_PK
	PRIMARY KEY (CL_FID),
	CONSTRAINT CC_MANAGEDFILE_NAME_UQ
	UNIQUE (CL_DEVNAME, CL_NAME)
);

REVOKE ALL
ON TABLE TB_MANAGEDFILE
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_MANAGEDFILE
TO PTOAPP;

COMMENT ON TABLE TB_MANAGEDFILE
IS 'Managed file';

COMMENT ON COLUMN TB_MANAGEDFILE.CL_FID
IS 'File ID';

COMMENT ON COLUMN TB_MANAGEDFILE.CL_DEVNAME
IS 'Device name';

COMMENT ON COLUMN TB_MANAGEDFILE.CL_NAME
IS 'File name';

COMMENT ON COLUMN TB_MANAGEDFILE.CL_CDATE
IS 'Creation date';

COMMENT ON CONSTRAINT CC_MANAGEDFILE_PK
ON TB_MANAGEDFILE
IS 'Primary key of managed file';

COMMENT ON CONSTRAINT CC_MANAGEDFILE_NAME_UQ
ON TB_MANAGEDFILE
IS 'Name of file must be unique per device';

