CREATE SEQUENCE TB_MEMBER_UID_SEQ
START WITH 1;

REVOKE ALL
ON TABLE TB_MEMBER_UID_SEQ
FROM PUBLIC;

GRANT SELECT, UPDATE
ON TABLE TB_MEMBER_UID_SEQ
TO PTOAPP;

COMMENT ON SEQUENCE TB_MEMBER_UID_SEQ
IS 'Sequence for member UID';

CREATE TABLE TB_MEMBER (
	CL_UID			BIGINT
	DEFAULT NEXTVAL('TB_MEMBER_UID_SEQ'),
	CL_NAME			VARCHAR(400),
	CL_SURNAME		VARCHAR(400),
	CONSTRAINT CC_MEMBER_PK
	PRIMARY KEY (CL_UID)
);

REVOKE ALL
ON TABLE TB_MEMBER
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_MEMBER
TO PTOAPP;

COMMENT ON TABLE TB_MEMBER
IS 'Member of application, a physical person';

COMMENT ON COLUMN TB_MEMBER.CL_UID
IS 'User ID';

COMMENT ON COLUMN TB_MEMBER.CL_NAME
IS 'Name of the member';

COMMENT ON COLUMN TB_MEMBER.CL_SURNAME
IS 'Surname of the member';

COMMENT ON CONSTRAINT CC_MEMBER_PK
ON TB_MEMBER
IS 'Primary key of member';

