CREATE TABLE TB_MANAGEDFILEDEVDATA (
	CL_FID			BIGINT,
	CL_KEY			VARCHAR(400)
	NOT NULL,
	CL_VALUE		VARCHAR(3600)
	NOT NULL,
	CONSTRAINT CC_MANAGEDFILEDEVDATA_PK
	PRIMARY KEY (CL_FID, CL_KEY),
	CONSTRAINT CC_MANAGEDFILEDEVDATA_FILE_FK
	FOREIGN KEY (CL_FID)
	REFERENCES TB_MANAGEDFILE(CL_FID)
	ON DELETE CASCADE
);

REVOKE ALL
ON TABLE TB_MANAGEDFILEDEVDATA
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_MANAGEDFILEDEVDATA
TO PTOAPP;

COMMENT ON TABLE TB_MANAGEDFILEDEVDATA
IS 'Device specific data entry of managed file';

COMMENT ON COLUMN TB_MANAGEDFILEDEVDATA.CL_FID
IS 'Managed file ID';

COMMENT ON COLUMN TB_MANAGEDFILEDEVDATA.CL_KEY
IS 'Data key';

COMMENT ON COLUMN TB_MANAGEDFILEDEVDATA.CL_VALUE
IS 'Data value';

COMMENT ON CONSTRAINT CC_MANAGEDFILEDEVDATA_PK
ON TB_MANAGEDFILEDEVDATA
IS 'Primary key of device specific data entry';

COMMENT ON CONSTRAINT CC_MANAGEDFILEDEVDATA_FILE_FK
ON TB_MANAGEDFILEDEVDATA
IS 'Managed file must be an existing one';

