CREATE SEQUENCE TB_MEMBER_UID_SEQ
START WITH 1;

REVOKE ALL
ON TABLE TB_MEMBER_UID_SEQ
FROM PUBLIC;

GRANT SELECT, UPDATE
ON TABLE TB_MEMBER_UID_SEQ
TO PTOAPP;

COMMENT ON SEQUENCE TB_MEMBER_UID_SEQ
IS 'Sequence for member UID';

CREATE TABLE TB_MEMBER (
	CL_UID			BIGINT
	DEFAULT NEXTVAL('TB_MEMBER_UID_SEQ'),
	CL_REF			CHAR(20)
	NOT NULL,
	CL_PHOTOFILE	BIGINT,
	CL_NAME			VARCHAR(400),
	CL_SURNAME		VARCHAR(400),
	CONSTRAINT CC_MEMBER_PK
	PRIMARY KEY (CL_UID),
	CONSTRAINT CC_MEMBER_REF_UQ
	UNIQUE (CL_REF),
	CONSTRAINT CC_MEMBER_PHOTOFILE_FK
	FOREIGN KEY (CL_PHOTOFILE)
	REFERENCES TB_MANAGEDFILE(CL_FID)
	ON DELETE SET NULL
);

REVOKE ALL
ON TABLE TB_MEMBER
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_MEMBER
TO PTOAPP;

COMMENT ON TABLE TB_MEMBER
IS 'Member of application, a physical person';

COMMENT ON COLUMN TB_MEMBER.CL_UID
IS 'User ID';

COMMENT ON COLUMN TB_MEMBER.CL_REF
IS 'Reference of the member';

COMMENT ON COLUMN TB_MEMBER.CL_PHOTOFILE
IS 'File identifier of member photo, if any';

COMMENT ON COLUMN TB_MEMBER.CL_NAME
IS 'Name of the member';

COMMENT ON COLUMN TB_MEMBER.CL_SURNAME
IS 'Surname of the member';

COMMENT ON CONSTRAINT CC_MEMBER_PK
ON TB_MEMBER
IS 'Primary key of member';

COMMENT ON CONSTRAINT CC_MEMBER_REF_UQ
ON TB_MEMBER
IS 'Reference of member';

COMMENT ON CONSTRAINT CC_MEMBER_PHOTOFILE_FK
ON TB_MEMBER
IS 'Photo file must be an existing file';

