CREATE TABLE TB_MEMBERCRED (
	CL_UID			BIGINT,
	CL_INDEX		INTEGER,
	CL_NAME			VARCHAR(2048) NOT NULL,
	CL_TYPE			INTEGER NOT NULL,
	CL_PASSWD		BYTEA NOT NULL,
	CONSTRAINT CC_MEMBERCRED_PK
	PRIMARY KEY (CL_UID, CL_INDEX),
	CONSTRAINT CC_MEMBERCRED_UID_FK
	FOREIGN KEY (CL_UID)
	REFERENCES TB_MEMBER(CL_UID),
	CONSTRAINT CC_MEMBERCRED_NAME_UQ
	UNIQUE (CL_NAME)
);

REVOKE ALL
ON TABLE TB_MEMBERCRED
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_MEMBERCRED
TO PTOAPP;

COMMENT ON TABLE TB_MEMBERCRED
IS 'Member credential';

COMMENT ON COLUMN TB_MEMBERCRED.CL_UID
IS 'Owner member UID';

COMMENT ON COLUMN TB_MEMBERCRED.CL_INDEX
IS 'Credential index';

COMMENT ON COLUMN TB_MEMBERCRED.CL_NAME
IS 'Member account name';

COMMENT ON COLUMN TB_MEMBERCRED.CL_TYPE
IS 'Credential type: 1. Password; 2. Certificate';

COMMENT ON COLUMN TB_MEMBERCRED.CL_PASSWD
IS 'Password value, if any';

COMMENT ON CONSTRAINT CC_MEMBERCRED_PK
ON TB_MEMBERCRED
IS 'Primary key of member credential';

COMMENT ON CONSTRAINT CC_MEMBERCRED_UID_FK
ON TB_MEMBERCRED
IS 'Member credential is only for an existing member';

COMMENT ON CONSTRAINT CC_MEMBERCRED_NAME_UQ
ON TB_MEMBERCRED
IS 'Cannot be more than one credential with the same name';

