CREATE TABLE TB_PROFILETRAIN (
	CL_REF			BIGINT,
	CONSTRAINT CC_PROFILETRAIN_PK
	PRIMARY KEY (CL_REF),
	CONSTRAINT CC_PROFILETRAIN_PROF_FK
	FOREIGN KEY (CL_REF)
	REFERENCES TB_PROFILE(CL_REF)
);

REVOKE ALL
ON TABLE TB_PROFILETRAIN
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_PROFILETRAIN
TO PTOAPP;

COMMENT ON TABLE TB_PROFILETRAIN
IS 'Trainer profile of a member';

COMMENT ON COLUMN TB_PROFILETRAIN.CL_REF
IS 'Profile reference';

COMMENT ON CONSTRAINT CC_PROFILETRAIN_PK
ON TB_PROFILETRAIN
IS 'Primary key of trainer profile';

COMMENT ON CONSTRAINT CC_PROFILETRAIN_PROF_FK
ON TB_PROFILETRAIN
IS 'This is an extension of profile';

