CREATE TABLE TB_PROFILECAND (
	CL_OWNERUID		BIGINT,
	CL_TYPE			INTEGER,
	CONSTRAINT CC_PROFILECAND_PK
	PRIMARY KEY (CL_OWNERUID, CL_TYPE),
	CONSTRAINT CC_PROFILECAND_PROF_FK
	FOREIGN KEY (CL_OWNERUID, CL_TYPE)
	REFERENCES TB_PROFILE(CL_OWNERUID, CL_TYPE)
);

REVOKE ALL
ON TABLE TB_PROFILECAND
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_PROFILECAND
TO PTOAPP;

COMMENT ON TABLE TB_PROFILECAND
IS 'Candidate profile of a member';

COMMENT ON COLUMN TB_PROFILECAND.CL_OWNERUID
IS 'Owner member UID';

COMMENT ON COLUMN TB_PROFILECAND.CL_TYPE
IS 'Type of profile';

COMMENT ON CONSTRAINT CC_PROFILECAND_PK
ON TB_PROFILECAND
IS 'Primary key of candidate profile';

COMMENT ON CONSTRAINT CC_PROFILECAND_PROF_FK
ON TB_PROFILECAND
IS 'Candidate profile is an existing profile';

