CREATE TABLE TB_PROFILECAND (
	CL_REF			BIGINT,
	CONSTRAINT CC_PROFILECAND_PK
	PRIMARY KEY (CL_REF),
	CONSTRAINT CC_PROFILECAND_PROF_FK
	FOREIGN KEY (CL_REF)
	REFERENCES TB_PROFILE(CL_REF)
);

REVOKE ALL
ON TABLE TB_PROFILECAND
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_PROFILECAND
TO PTOAPP;

COMMENT ON TABLE TB_PROFILECAND
IS 'Candidate profile of a member';

COMMENT ON COLUMN TB_PROFILECAND.CL_REF
IS 'Profile reference';

COMMENT ON CONSTRAINT CC_PROFILECAND_PK
ON TB_PROFILECAND
IS 'Primary key of candidate profile';

COMMENT ON CONSTRAINT CC_PROFILECAND_PROF_FK
ON TB_PROFILECAND
IS 'This is an extension of profile';

