CREATE SEQUENCE TB_PROFILE_REF_SEQ
START WITH 1;

REVOKE ALL
ON TABLE TB_PROFILE_REF_SEQ
FROM PUBLIC;

GRANT SELECT, UPDATE
ON TABLE TB_PROFILE_REF_SEQ
TO PTOAPP;

COMMENT ON SEQUENCE TB_PROFILE_REF_SEQ
IS 'Sequence for profile reference';

CREATE TABLE TB_PROFILE (
	CL_REF			BIGINT
	DEFAULT NEXTVAL('TB_PROFILE_REF_SEQ'),
	CL_OWNERUID		BIGINT NOT NULL,
	CL_ROLE			INTEGER NOT NULL,
	CL_COUNTRY		INTEGER NOT NULL,
	CL_FIELD		INTEGER NOT NULL,
	CL_SPECIAL		INTEGER,
	CONSTRAINT CC_PROFILE_PK
	PRIMARY KEY (CL_REF),
	CONSTRAINT CC_PROFILE_OWNUID_FK
	FOREIGN KEY (CL_OWNERUID)
	REFERENCES TB_MEMBER(CL_UID),
	CONSTRAINT CC_PROFILE_TYPE_UQ
	UNIQUE (CL_OWNERUID, CL_ROLE, CL_COUNTRY, CL_FIELD, CL_SPECIAL)
);

REVOKE ALL
ON TABLE TB_PROFILE
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_PROFILE
TO PTOAPP;

COMMENT ON TABLE TB_PROFILE
IS 'Profile of a member';

COMMENT ON COLUMN TB_PROFILE.CL_REF
IS 'Profile reference';

COMMENT ON COLUMN TB_PROFILE.CL_OWNERUID
IS 'Owner member UID';

COMMENT ON COLUMN TB_PROFILE.CL_ROLE
IS 'Role of profile';

COMMENT ON COLUMN TB_PROFILE.CL_COUNTRY
IS 'Country of profile';

COMMENT ON COLUMN TB_PROFILE.CL_FIELD
IS 'Field of profile';

COMMENT ON COLUMN TB_PROFILE.CL_SPECIAL
IS 'Specialization of profile';

COMMENT ON CONSTRAINT CC_PROFILE_PK
ON TB_PROFILE
IS 'Primary key of profile';

COMMENT ON CONSTRAINT CC_PROFILE_OWNUID_FK
ON TB_PROFILE
IS 'Profile is only for an existing member';

COMMENT ON CONSTRAINT CC_PROFILE_TYPE_UQ
ON TB_PROFILE
IS 'Only one profile of the same type per member';

