CREATE TABLE TB_PROFILETRAIN (
	CL_OWNERUID		BIGINT,
	CL_TYPE			INTEGER,
	CONSTRAINT CC_PROFILETRAIN_PK
	PRIMARY KEY (CL_OWNERUID, CL_TYPE),
	CONSTRAINT CC_PROFILETRAIN_PROF_FK
	FOREIGN KEY (CL_OWNERUID, CL_TYPE)
	REFERENCES TB_PROFILE(CL_OWNERUID, CL_TYPE)
);

REVOKE ALL
ON TABLE TB_PROFILECAND
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_PROFILETRAIN
TO PTOAPP;

COMMENT ON TABLE TB_PROFILETRAIN
IS 'Trainer profile of a member';

COMMENT ON COLUMN TB_PROFILETRAIN.CL_OWNERUID
IS 'Owner member UID';

COMMENT ON COLUMN TB_PROFILETRAIN.CL_TYPE
IS 'Type of profile';

COMMENT ON CONSTRAINT CC_PROFILETRAIN_PK
ON TB_PROFILETRAIN
IS 'Primary key of trainer profile';

COMMENT ON CONSTRAINT CC_PROFILETRAIN_PROF_FK
ON TB_PROFILETRAIN
IS 'Trainer profile is an existing profile';

