CREATE TABLE TB_REQDIRPROFTOKEN (
	CL_REF			BIGINT,
	CL_REQCREF		BIGINT,
	CONSTRAINT CC_REQDIRPROFTOKEN_PK
	PRIMARY KEY (CL_REF),
	CONSTRAINT CC_REQDIRPROFTOKEN_TOKEN_FK
	FOREIGN KEY (CL_REF)
	REFERENCES TB_AUTHTOKEN(CL_REF),
	CONSTRAINT CC_REQDIRPROFTOKEN_REQC_FK
	FOREIGN KEY (CL_REQCREF)
	REFERENCES TB_REQCRED(CL_REF)
);

REVOKE ALL
ON TABLE TB_REQDIRPROFTOKEN
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_REQDIRPROFTOKEN
TO PTOAPP;

COMMENT ON TABLE TB_REQDIRPROFTOKEN
IS 'Token of request for direct profiles';

COMMENT ON COLUMN TB_REQDIRPROFTOKEN.CL_REF
IS 'Token reference';

COMMENT ON COLUMN TB_REQDIRPROFTOKEN.CL_REQCREF
IS 'Request for direct profiles reference';

COMMENT ON CONSTRAINT CC_REQDIRPROFTOKEN_PK
ON TB_REQDIRPROFTOKEN
IS 'Primary key of token of request for direct profiles';

COMMENT ON CONSTRAINT CC_REQDIRPROFTOKEN_TOKEN_FK
ON TB_REQDIRPROFTOKEN
IS 'Token must be an existing token';

COMMENT ON CONSTRAINT CC_REQDIRPROFTOKEN_REQC_FK
ON TB_REQDIRPROFTOKEN
IS 'Request for credential must be an existing request';

