CREATE TABLE TB_REQPROFTOKEN (
	CL_REF			BIGINT,
	CL_OWNERUID		BIGINT,
	CL_REQREF		BIGINT,
	CONSTRAINT CC_REQPROFTOKEN_PK
	PRIMARY KEY (CL_REF),
	CONSTRAINT CC_REQPROFTOKEN_TOKEN_FK
	FOREIGN KEY (CL_REF)
	REFERENCES TB_AUTHTOKEN(CL_REF),
	CONSTRAINT CC_REQPROFTOKEN_OWNER_FK
	FOREIGN KEY (CL_OWNERUID)
	REFERENCES TB_MEMBER(CL_UID),
	CONSTRAINT CC_REQPROFTOKEN_REQ_FK
	FOREIGN KEY (CL_REQREF)
	REFERENCES TB_REQPROF(CL_REF)
);

REVOKE ALL
ON TABLE TB_REQPROFTOKEN
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_REQPROFTOKEN
TO PTOAPP;

COMMENT ON TABLE TB_REQPROFTOKEN
IS 'Token of request for profile';

COMMENT ON COLUMN TB_REQPROFTOKEN.CL_REF
IS 'Token reference';

COMMENT ON COLUMN TB_REQPROFTOKEN.CL_OWNERUID
IS 'Owner user ID';

COMMENT ON COLUMN TB_REQPROFTOKEN.CL_REQREF
IS 'Request for profile reference';

COMMENT ON CONSTRAINT CC_REQPROFTOKEN_PK
ON TB_REQPROFTOKEN
IS 'Primary key of token of request for profile';

COMMENT ON CONSTRAINT CC_REQPROFTOKEN_TOKEN_FK
ON TB_REQPROFTOKEN
IS 'Token must be an existing token';

COMMENT ON CONSTRAINT CC_REQPROFTOKEN_OWNER_FK
ON TB_REQPROFTOKEN
IS 'Owner must be an existing member';

COMMENT ON CONSTRAINT CC_REQPROFTOKEN_REQ_FK
ON TB_REQPROFTOKEN
IS 'Request must be an existing request';

