CREATE TABLE TB_REQDIRPROFTOKENREQP (
	CL_REQDPTOKENREF	BIGINT,
	CL_REQPREF			BIGINT,
	CONSTRAINT CC_REQDIRPROFTOKENREQP_PK
	PRIMARY KEY (CL_REQDPTOKENREF, CL_REQPREF),
	CONSTRAINT CC_REQDIRPROFTOKENREQP_REQDPTOKEN_FK
	FOREIGN KEY (CL_REQDPTOKENREF)
	REFERENCES TB_REQDIRPROFTOKEN(CL_REF),
	CONSTRAINT CC_REQDIRPROFTOKENREQP_REQP_FK
	FOREIGN KEY (CL_REQPREF)
	REFERENCES TB_REQPROF(CL_REF)
);

REVOKE ALL
ON TABLE TB_REQDIRPROFTOKENREQP
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_REQDIRPROFTOKENREQP
TO PTOAPP;

COMMENT ON TABLE TB_REQDIRPROFTOKENREQP
IS 'Requests for profile of request for direct profiles';

COMMENT ON COLUMN TB_REQDIRPROFTOKENREQP.CL_REQDPTOKENREF
IS 'Request for direct profiles token reference';

COMMENT ON COLUMN TB_REQDIRPROFTOKENREQP.CL_REQPREF
IS 'Request for profile reference';

COMMENT ON CONSTRAINT CC_REQDIRPROFTOKENREQP_PK
ON TB_REQDIRPROFTOKENREQP
IS 'Primary key of relationship';

COMMENT ON CONSTRAINT CC_REQDIRPROFTOKENREQP_REQDPTOKEN_FK
ON TB_REQDIRPROFTOKENREQP
IS 'Token must be an existing request for direct profiles token';

COMMENT ON CONSTRAINT CC_REQDIRPROFTOKENREQP_REQP_FK
ON TB_REQDIRPROFTOKENREQP
IS 'Request for profile must be an existing request';

