CREATE SEQUENCE TB_REQCRED_REF_SEQ
START WITH 1;

REVOKE ALL
ON TABLE TB_REQCRED_REF_SEQ
FROM PUBLIC;

GRANT SELECT, UPDATE
ON TABLE TB_REQCRED_REF_SEQ
TO PTOAPP;

COMMENT ON SEQUENCE TB_REQCRED_REF_SEQ
IS 'Sequence for request for credential reference';

CREATE TABLE TB_REQCRED (
	CL_REF			BIGINT
	DEFAULT NEXTVAL('TB_REQCRED_REF_SEQ'),
	CL_TYPE			INTEGER NOT NULL,
	CL_MAIL			VARCHAR(1024),
	CL_PASSWORD		BYTEA,
	CONSTRAINT CC_REQCRED_PK
	PRIMARY KEY (CL_REF)
);

REVOKE ALL
ON TABLE TB_REQCRED
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_REQCRED
TO PTOAPP;

COMMENT ON TABLE TB_REQCRED
IS 'Request for credential';

COMMENT ON COLUMN TB_REQCRED.CL_REF
IS 'Request reference';

COMMENT ON COLUMN TB_REQCRED.CL_TYPE
IS 'Request type';

COMMENT ON COLUMN TB_REQCRED.CL_MAIL
IS 'Member e-mail';

COMMENT ON COLUMN TB_REQCRED.CL_PASSWORD
IS 'Early given password';

COMMENT ON CONSTRAINT CC_REQCRED_PK
ON TB_REQCRED
IS 'Primary key of request for credential';

