CREATE TABLE TB_REQCREDMAIL (
	CL_MAIL			VARCHAR(1024),
	CL_PASSWORD		BYTEA,
	CL_TOKEN		BYTEA NOT NULL,
	CL_CREATION		DATE NOT NULL,
	CONSTRAINT CC_REQCREDMAIL_PK
	PRIMARY KEY (CL_MAIL)
);

REVOKE ALL
ON TABLE TB_REQCREDMAIL
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE TB_REQCREDMAIL
TO PTOAPP;

COMMENT ON TABLE TB_REQCREDMAIL
IS 'Credential mail request';

COMMENT ON COLUMN TB_REQCREDMAIL.CL_MAIL
IS 'Member e-mail';

COMMENT ON COLUMN TB_REQCREDMAIL.CL_PASSWORD
IS 'Early given password';

COMMENT ON COLUMN TB_REQCREDMAIL.CL_TOKEN
IS 'Accreditation token';

COMMENT ON COLUMN TB_REQCREDMAIL.CL_CREATION
IS 'Creation date';

COMMENT ON CONSTRAINT CC_REQCREDMAIL_PK
ON TB_REQCREDMAIL
IS 'Primary key of credential mail request';

