CREATE VIEW VW_MEMBERGROUP AS
SELECT
	CL_UID,
	'member'::VARCHAR(2048) AS CL_NAME
FROM TB_MEMBER;

REVOKE ALL
ON VW_MEMBERGROUP
FROM PUBLIC;

GRANT SELECT
ON VW_MEMBERGROUP
TO PTOAPP;

COMMENT ON VIEW VW_MEMBERGROUP
IS 'Member groups';

COMMENT ON COLUMN VW_MEMBERGROUP.CL_UID
IS 'Associated member UID';

COMMENT ON COLUMN VW_MEMBERGROUP.CL_NAME
IS 'Group name';

